services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: astro_app
    command: bun dev
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - blog

  db:
    # https://www.cockroachlabs.com/docs/v25.2/start-a-local-cluster-in-docker-linux#start-a-single-node-cluster
    # https://hub.docker.com/r/cockroachdb/cockroach
    image: cockroachdb/cockroach:latest
    container_name: astro_db
    environment:
      COCKROACH_USER: ${COCKROACH_USER}
      COCKROACH_PASSWORD: ${COCKROACH_PASSWORD}
      COCKROACH_DATABASE: ${COCKROACH_DATABASE}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db:/cockroachdb/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - blog
    command: >
      start-single-node


volumes:
  db:

networks:
  blog:
    driver: bridge