version: "3.9"

services:
  db:
    image: postgres:16
    container_name: astro_db
    environment:
      POSTGRES_USER: astro
      POSTGRES_PASSWORD: astro_pass
      POSTGRES_DB: astro_db
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: