-- CreateEnum
CREATE TYPE "DevLangCode" AS ENUM ('JS', 'TS', 'GAS');

-- CreateEnum
CREATE TYPE "FrameworkCode" AS ENUM ('REACT', 'ASTRO', 'HONO', 'TAILWIND');

-- CreateTable
CREATE TABLE "tags" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "name" STRING(128) NOT NULL,

    CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tweets" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "content" STRING(1024) NOT NULL,
    "article" STRING(16384),
    "author" STRING(128),
    "ip_address" STRING(32),
    "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tweets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tweets_tags" (
    "tweet_id" INT8 NOT NULL,
    "tag_id" INT8 NOT NULL,

    CONSTRAINT "tweets_tags_pkey" PRIMARY KEY ("tweet_id","tag_id")
);

-- CreateTable
CREATE TABLE "vector" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "source_id" INT8 NOT NULL,
    "source_table" STRING(128) NOT NULL,
    "embedding" STRING NOT NULL,

    CONSTRAINT "vector_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Tweet" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "content" STRING NOT NULL,
    "article" STRING,
    "author" STRING,
    "ip_address" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Tweet_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Tag" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "Tag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TweetVector" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tweet_id" INT4 NOT NULL,
    "embedding" STRING NOT NULL,

    CONSTRAINT "TweetVector_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Article" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "body" STRING NOT NULL,
    "author" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Article_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DevLangRelation" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" "DevLangCode" NOT NULL,

    CONSTRAINT "DevLangRelation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FrameworkRelation" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" "FrameworkCode" NOT NULL,

    CONSTRAINT "FrameworkRelation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Infra" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "Infra_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title_en" STRING NOT NULL,
    "title_ja" STRING NOT NULL,
    "thumbnail" STRING,
    "body" JSONB,
    "github" STRING,
    "href" STRING,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_TagToTweet" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_ArticleToTag" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_DevLangRelationToProduct" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_FrameworkRelationToProduct" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_InfraToProduct" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "tags_name_key" ON "tags"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Tag_name_key" ON "Tag"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Infra_name_key" ON "Infra"("name");

-- CreateIndex
CREATE UNIQUE INDEX "_TagToTweet_AB_unique" ON "_TagToTweet"("A", "B");

-- CreateIndex
CREATE INDEX "_TagToTweet_B_index" ON "_TagToTweet"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ArticleToTag_AB_unique" ON "_ArticleToTag"("A", "B");

-- CreateIndex
CREATE INDEX "_ArticleToTag_B_index" ON "_ArticleToTag"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_DevLangRelationToProduct_AB_unique" ON "_DevLangRelationToProduct"("A", "B");

-- CreateIndex
CREATE INDEX "_DevLangRelationToProduct_B_index" ON "_DevLangRelationToProduct"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_FrameworkRelationToProduct_AB_unique" ON "_FrameworkRelationToProduct"("A", "B");

-- CreateIndex
CREATE INDEX "_FrameworkRelationToProduct_B_index" ON "_FrameworkRelationToProduct"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_InfraToProduct_AB_unique" ON "_InfraToProduct"("A", "B");

-- CreateIndex
CREATE INDEX "_InfraToProduct_B_index" ON "_InfraToProduct"("B");

-- AddForeignKey
ALTER TABLE "tweets_tags" ADD CONSTRAINT "tweets_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tweets_tags" ADD CONSTRAINT "tweets_tags_tweet_id_fkey" FOREIGN KEY ("tweet_id") REFERENCES "tweets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "vector" ADD CONSTRAINT "vector_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "tweets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "TweetVector" ADD CONSTRAINT "TweetVector_tweet_id_fkey" FOREIGN KEY ("tweet_id") REFERENCES "Tweet"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TagToTweet" ADD CONSTRAINT "_TagToTweet_A_fkey" FOREIGN KEY ("A") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TagToTweet" ADD CONSTRAINT "_TagToTweet_B_fkey" FOREIGN KEY ("B") REFERENCES "Tweet"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ArticleToTag" ADD CONSTRAINT "_ArticleToTag_A_fkey" FOREIGN KEY ("A") REFERENCES "Article"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ArticleToTag" ADD CONSTRAINT "_ArticleToTag_B_fkey" FOREIGN KEY ("B") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_DevLangRelationToProduct" ADD CONSTRAINT "_DevLangRelationToProduct_A_fkey" FOREIGN KEY ("A") REFERENCES "DevLangRelation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_DevLangRelationToProduct" ADD CONSTRAINT "_DevLangRelationToProduct_B_fkey" FOREIGN KEY ("B") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_FrameworkRelationToProduct" ADD CONSTRAINT "_FrameworkRelationToProduct_A_fkey" FOREIGN KEY ("A") REFERENCES "FrameworkRelation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_FrameworkRelationToProduct" ADD CONSTRAINT "_FrameworkRelationToProduct_B_fkey" FOREIGN KEY ("B") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_InfraToProduct" ADD CONSTRAINT "_InfraToProduct_A_fkey" FOREIGN KEY ("A") REFERENCES "Infra"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_InfraToProduct" ADD CONSTRAINT "_InfraToProduct_B_fkey" FOREIGN KEY ("B") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
